// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeSystem.Models.Database;

#nullable disable

namespace ResumeSystem.Migrations
{
    [DbContext(typeof(ResumeContext))]
    partial class ResumeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.Property<int>("CandidatesCandidateID")
                        .HasColumnType("int");

                    b.Property<int>("SkillsSkillID")
                        .HasColumnType("int");

                    b.HasKey("CandidatesCandidateID", "SkillsSkillID");

                    b.HasIndex("SkillsSkillID");

                    b.ToTable("CandidateSkill");
                });

            modelBuilder.Entity("ResumeSystem.Models.Database.Candidate", b =>
                {
                    b.Property<int>("CandidateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateID"));

                    b.Property<string>("CAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAN_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAN_PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateID");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("ResumeSystem.Models.Database.Resume", b =>
                {
                    b.Property<int>("ResumeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResumeID"));

                    b.Property<int>("CandidateID")
                        .HasColumnType("int");

                    b.Property<string>("RESUME_STRING")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESUME_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResumeID");

                    b.HasIndex("CandidateID");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("ResumeSystem.Models.Database.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<string>("SKILL_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ResumeSystem.Models.Database.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.HasOne("ResumeSystem.Models.Database.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidatesCandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeSystem.Models.Database.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsSkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeSystem.Models.Database.Resume", b =>
                {
                    b.HasOne("ResumeSystem.Models.Database.Candidate", "Candidate")
                        .WithMany("Resumes")
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("ResumeSystem.Models.Database.Candidate", b =>
                {
                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
